# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SpringBoot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-ordering-system    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD        

    - name: Build and Push product-service
      run: |
        if [ -f product-service/pom.xml ]; then
          mvn -B package dockerfile:push --file product-service/pom.xml
        else
          echo "Skipping product-service: product-service/pom.xml not found"
        fi
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push payment-service
      run: |
        if [ -f payment-service/pom.xml ]; then
          mvn -B package dockerfile:push --file payment-service/pom.xml
        else
          echo "Skipping payment-service: payment-service/pom.xml not found"
        fi
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push order-service
      run: |
        if [ -f order-service/pom.xml ]; then
          mvn -B package dockerfile:push --file order-service/pom.xml
        else
          echo "Skipping order-service: order-service/pom.xml not found"
        fi
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push config-server
      run: |
        if [ -f config-server/pom.xml ]; then
          mvn -B package dockerfile:push --file config-server/pom.xml
        else
          echo "Skipping config-server: config-server/pom.xml not found"
        fi
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push cloud-gateway
      run: |
        if [ -f cloud-gateway/pom.xml ]; then
          mvn -B package dockerfile:push --file cloud-gateway/pom.xml
        else
          echo "Skipping cloud-gateway: cloud-gateway/pom.xml not found"
        fi
      env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}   # raw JSON ok
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: cluster-ordering-system
          location: us-central1-c
      - name: kubectl apply
        run: kubectl apply -f k8s/

